### ISSUE TITLE
Document all command line switches for quickstart create

### ISSUE THREAD

**Issue by Cito** [zatosource/zato-docs#25]
On the page https://zato.io/docs/admin/cli/quickstart-create.html, some more command line switches for the `zato quickstart create` command should be documented (added to that table with description and examples):

```
-h
--store-log
--verbose
--store-config
--cluster_name
--servers
```

**Comment by Cito** [comment]
Also, in the changelog further down the page it should be `--cluster_name` instead of `--cluster-name`.

**Comment by Cito** [comment]
Sorry, I overlooked that the docs only list the command-specific parameters which is a good idea because it makes the docs less bloated. The first four are not command-specific, but apply to all zato commands. So I have sent a pull request only for the 2 new ones.

**Comment by dsuch** [comment]
Mass-closing old tickets.
