### ISSUE TITLE
field 'engine' for internal service 'zato.outgoing.sql.create' has wrong values in doc (for MySQL)

### ISSUE THREAD

**Issue by pedrudehuere** [zatosource/zato-docs#29]
The [doc](https://zato.io/docs/public-api/details/zato.outgoing.sql.create.html) says 

```
engine: string - Database engine, its type. Must be one one of ‘oracle’, ‘postgresql’, ‘mysql’ or ‘sqlite’.
```

But in fact I need to put 'mysql+pymysql' to make it work (only tested with MySQL)

**Comment by dsuch** [comment]
Mass-closing old tickets.
