### ISSUE TITLE
Socket method is not documented in outgoing zeroMQ documentation

### ISSUE THREAD

**Issue by MikHulk** [zatosource/zato-docs#45]
Hello,

the related page is: https://zato.io/docs/web-admin/outgoing/zmq.html

What I see on the admin interface:

![capt](https://user-images.githubusercontent.com/10364941/55279025-ebf9a000-5313-11e9-9326-f923e50bdef5.png)

Regards

**Comment by dsuch** [comment]
Thank you for this ticket and all the other ones that you opened, @MikHulk!

In June this year we will have [a new release](https://zato.io/docs/release/policy.html). Around May and June I will be working on new documentation, including new tutorials and other information.

I will be sure to include information from your tickets during these works - thanks again.

**Comment by dsuch** [comment]
Mass-closing old tickets.
